# Generated by Django 5.1.2 on 2024-10-30 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mlmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
